name: CI

on:
  pull_request:
    branches:
<<<<<<< HEAD
<<<<<<< HEAD
      - main
=======
      - master
>>>>>>> f33594e3ef75ff367ca088f0f5c44a7f5fcd45b1
=======
      - main
>>>>>>> 717a29035e3b13a218a05901d5e6d280b67148f3

jobs:
  lint-analyze-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, dom, curl, libxml, pdo, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run linting
        run: composer lint

      - name: Run static analysis
        run: composer analyze

      - name: Run tests
<<<<<<< HEAD
<<<<<<< HEAD
        run: composer test
=======
        run: composer test

>>>>>>> f33594e3ef75ff367ca088f0f5c44a7f5fcd45b1
=======
        run: composer test
>>>>>>> 717a29035e3b13a218a05901d5e6d280b67148f3
