name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  lint-analyze-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, dom, curl, libxml, pdo, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-suggest

      - name: Run linting
        run: composer lint

      - name: Run static analysis
        run: composer analyze

      - name: Run tests
        run: composer test

